backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: pages_en
    label: Pages (English)
    editor:
      preview: true
    files:
      - file: "content/pages/en/home.md"
        label: Home Page
        name: home_en
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Tagline, name: tagline, widget: string, hint: "Short hero message." }
          - { label: Body, name: body, widget: markdown }
      - file: "content/pages/en/about.md"
        label: About Page
        name: about_en
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: text }
          - { label: Body, name: body, widget: markdown }
  - name: pages_ar
    label: "صفحات (العربية)"
    editor:
      preview: true
    files:
      - file: "content/pages/ar/home.md"
        label: "الصفحة الرئيسية"
        name: home_ar
        fields:
          - { label: "العنوان", name: title, widget: string }
          - { label: "السطر التعريفي", name: tagline, widget: string }
          - { label: "المحتوى", name: body, widget: markdown }
      - file: "content/pages/ar/about.md"
        label: "صفحة نبذة عنا"
        name: about_ar
        fields:
          - { label: "العنوان", name: title, widget: string }
          - { label: "مقدمة", name: intro, widget: text }
          - { label: "المحتوى", name: body, widget: markdown }
  - name: blog_en
    label: Blog Posts (English)
    folder: "content/blog/en"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Description, name: description, widget: text }
      - { label: Featured Image, name: image, widget: image, choose_url: true, media_folder: "public/uploads", public_folder: "/uploads" }
      - { label: Image Alt Text, name: imageAlt, widget: string, required: false }
      - { label: Body, name: body, widget: markdown }
  - name: blog_ar
    label: "مقالات المدونة (العربية)"
    folder: "content/blog/ar"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: title, widget: string }
      - { label: "تاريخ النشر", name: date, widget: datetime }
      - { label: "الوصف", name: description, widget: text }
      - { label: "الصورة البارزة", name: image, widget: image, choose_url: true, media_folder: "public/uploads", public_folder: "/uploads" }
      - { label: "نص بديل للصورة", name: imageAlt, widget: string, required: false }
      - { label: "المحتوى", name: body, widget: markdown }
  - name: news_en
    label: News (English)
    folder: "content/news/en"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Summary, name: summary, widget: text }
      - { label: Featured Image, name: image, widget: image, choose_url: true, media_folder: "public/uploads", public_folder: "/uploads" }
      - { label: Image Alt Text, name: imageAlt, widget: string, required: false }
      - { label: Link, name: link, widget: string, required: false, hint: "Optional URL for the full story." }
  - name: news_ar
    label: "الأخبار (العربية)"
    folder: "content/news/ar"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: title, widget: string }
      - { label: "تاريخ النشر", name: date, widget: datetime }
      - { label: "الملخص", name: summary, widget: text }
      - { label: "الصورة البارزة", name: image, widget: image, choose_url: true, media_folder: "public/uploads", public_folder: "/uploads" }
      - { label: "نص بديل للصورة", name: imageAlt, widget: string, required: false }
      - { label: "الرابط", name: link, widget: string, required: false, hint: "رابط اختياري للخبر الكامل." }
